# Generated by Django 5.0.4 on 2024-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_analyst_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='eventId',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
