# Generated by Django 5.0.4 on 2024-05-21 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_analyst_api', '0002_rename_eventid_photo_event_alter_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$'), django.core.validators.MinLengthValidator(3, message='Username must be at least 3 characters long')]),
        ),
    ]
