# Generated by Django 5.0.4 on 2024-05-10 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_analyst_api', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^(?=.*[a-zA-Z])(?=.*\\d)[A-Za-z\\d@$!%*?&]+$'), django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$'), django.core.validators.MinLengthValidator(4, message='Password must be at least 6 characters long')]),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
