# Generated by Django 5.0.4 on 2024-05-29 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_analyst_api', '0005_alter_event_description_alter_event_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatistic',
            fields=[
                ('eventStatisticId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genderAnalysis', models.JSONField(default=dict)),
                ('raceAnalysis', models.JSONField(default=dict)),
                ('ageAnalysis', models.JSONField(default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_analyst_api.event')),
            ],
        ),
    ]
